import React,{Component,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Canvas,useThree,useFrame} from '@react-three/fiber';
import * as THREE from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import Model,{smooth,clamp} from './Model';
const body=document.body,host=document.querySelector('#scene'),journey=document.querySelector('.journey'),motion=document.querySelector('#motion'),media=matchMedia('(prefers-reduced-motion: reduce)');
const labels=['01 / UNE VISION D’ENSEMBLE','02 / AU SERVICE DES UTILISATEURS','03 / AU CŒUR DE VOTRE PARC','04 / PROTÉGER VOTRE ACTIVITÉ','05 / UNE EXPERTISE À 360°','06 / RETROUVEZ L’ESPRIT LIBRE'];
const control={progress:0,invalidate:()=>{}};let isStatic=media.matches,scheduled=0;
function progress(){scheduled=0;const top=-journey.getBoundingClientRect().top,chapters=[...document.querySelectorAll('.chapter')];let segment=0;for(let i=0;i<5;i++)if(top>=chapters[i].offsetTop)segment=i;const a=chapters[segment].offsetTop,b=chapters[Math.min(segment+1,5)].offsetTop;control.progress=isStatic?0:clamp((segment+clamp((top-a)/Math.max(1,b-a)))/5);const idx=Math.min(5,Math.round(control.progress*5));document.querySelector('#part-label').textContent=labels[idx];document.querySelectorAll('.rail nav a').forEach((a,i)=>{if(i===idx)a.setAttribute('aria-current','step');else a.removeAttribute('aria-current')});host.setAttribute('aria-label',`MacBook Pro 3D illustratif — ${labels[idx].split(' / ')[1].toLowerCase()}.`);control.invalidate()}
function schedule(){if(!scheduled)scheduled=requestAnimationFrame(progress)}
function mode(){body.classList.toggle('static',isStatic);motion.textContent=isStatic?'Activer le parcours animé':'Vue sans animation';motion.setAttribute('aria-pressed',String(isStatic));schedule()}
let fallbackStarted=false;
async function fallback(){if(fallbackStarted)return;fallbackStarted=true;body.classList.add('software');body.classList.remove('ready');try{const {startSoftware}=await import('./software.js?v=5');await startSoftware(host,control);schedule()}catch(error){console.warn('Rendu compatible indisponible',error);body.classList.add('no-webgl');isStatic=true;mode();motion.hidden=true;document.querySelector('#render-loading').textContent='L’ordinateur n’a pas pu se charger. Rechargez la page pour réessayer.';document.querySelector('#part-label').textContent='VOTRE SERVICE INFORMATIQUE'}}
mode();motion.addEventListener('click',()=>{isStatic=!isStatic;mode();document.querySelector('#approche').scrollIntoView({behavior:'instant'})});media.addEventListener('change',e=>{isStatic=e.matches;mode()});addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule()});
class Boundary extends Component{state={error:false};static getDerivedStateFromError(){return{error:true}}componentDidCatch(){fallback()}render(){return this.state.error?null:this.props.children}}
function Unavailable(){useEffect(fallback,[]);return null}
function Studio(){const {gl,scene,camera,size,invalidate}=useThree();useEffect(()=>{const pmrem=new THREE.PMREMGenerator(gl),room=new RoomEnvironment(),env=pmrem.fromScene(room,.04);scene.environment=env.texture;room.dispose();pmrem.dispose();control.invalidate=invalidate;body.classList.add('ready');invalidate();const loss=e=>{e.preventDefault();fallback()};gl.domElement.addEventListener('webglcontextlost',loss);return()=>{env.dispose();gl.domElement.removeEventListener('webglcontextlost',loss);control.invalidate=()=>{}}},[gl,scene,invalidate]);useEffect(()=>{schedule();invalidate()},[size.width,size.height,invalidate]);useFrame(()=>{const p=control.progress,spread=smooth(.025,.45,p)*(1-smooth(.81,1,p));const distance=Math.max(18.7,18.7/camera.aspect)*(1+.28*spread);camera.position.set(.5,.47,.72).normalize().multiplyScalar(distance);camera.lookAt(0,1.25+spread*.75,-.15);gl.toneMappingExposure=1.28});return <><ambientLight intensity={1.2}/><directionalLight position={[3,9,5]} intensity={3.8}/><directionalLight position={[-7,5,-3]} intensity={2.2} color="#91b7ff"/><directionalLight position={[1,-6,3]} intensity={1.3} color="#c8dbf8"/><Model control={control}/></>}
createRoot(host).render(<Boundary><Canvas frameloop="demand" dpr={[1,1.6]} resize={{debounce:0}} camera={{position:[9,8,13],fov:34,near:.1,far:100}} gl={{antialias:true,alpha:true,powerPreference:'default'}} fallback={<Unavailable/>}><Studio/></Canvas></Boundary>);
