// CPU fallback derived from Inside MacBook geometry (Pulkit Saraf, MIT).
import {PerspectiveCamera,Matrix4,Vector3} from 'three';
import {transforms} from './transforms';
const clamp=v=>Math.min(1,Math.max(0,v));const smooth=(a,b,p)=>{const t=clamp((p-a)/(b-a));return t*t*(3-2*t)};
const timing={display:[.025,.28],'top-case':[.025,.28],keyboard:[.055,.32],trackpad:[.055,.32],'bottom-cover':[.05,.3],'logic-board':[.2,.48],processor:[.29,.57],heatsink:[.25,.54],'left-fan':[.21,.47],'right-fan':[.21,.47],'battery-left':[.39,.64],'battery-center':[.39,.64],'battery-right':[.39,.64],'left-speaker':[.45,.73],'right-speaker':[.45,.73],'left-io':[.43,.7],'right-io':[.43,.7],magsafe:[.43,.7],'left-hinge':[.12,.42],'right-hinge':[.12,.42]};
export async function startSoftware(host,control){
 const response=await fetch(new URL('./model.json?v=5',import.meta.url));if(!response.ok)throw new Error('Modèle indisponible');const data=await response.json();
 const wrapper=document.createElement('div');wrapper.id='software-scene';wrapper.setAttribute('role','img');wrapper.setAttribute('aria-label','MacBook Pro en 3D : éclaté progressif au défilement');host.after(wrapper);
 const canvas=document.createElement('canvas');wrapper.append(canvas);const ctx=canvas.getContext('2d',{alpha:true});if(!ctx)throw new Error('Rendu indisponible');
 const camera=new PerspectiveCamera(34,1,.1,100),rotation=new Matrix4(),translate=new Matrix4(),world=new Matrix4(),view=new Matrix4();let pending=0,w=0,h=0;
 const rgb=color=>[parseInt(color.slice(0,2),16),parseInt(color.slice(2,4),16),parseInt(color.slice(4,6),16)];
 for(const part of data)for(const mesh of part.meshes)mesh.rgb=rgb(mesh.c);
 function draw(){pending=0;w=wrapper.clientWidth;h=wrapper.clientHeight;if(!w||!h)return;const dpr=Math.min(devicePixelRatio,1.5);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);camera.aspect=w/h;camera.updateProjectionMatrix();
 const p=control.progress,spread=smooth(.025,.45,p)*(1-smooth(.81,1,p)),distance=Math.max(18.7,18.7/camera.aspect)*(1+.28*spread);camera.position.set(.5,.47,.72).normalize().multiplyScalar(distance);camera.lookAt(0,1.25+spread*.75,-.15);camera.updateMatrixWorld(true);rotation.makeRotationY(-.16+smooth(.025,.72,p)*(1-smooth(.81,1,p))*.1);const faces=[];const f=1/Math.tan(34*Math.PI/360);
 for(const part of data){const t=transforms[part.id],time=timing[part.id],e=smooth(time[0],time[1],p)*(1-smooth(.81,1,p));translate.makeTranslation(...t.at.map((n,i)=>n+t.spread[i]*e));world.multiplyMatrices(rotation,translate);view.multiplyMatrices(camera.matrixWorldInverse,world);const m=view.elements;
 for(const mesh of part.meshes){const v=mesh.v,projected=new Float32Array(v.length/3*5);for(let i=0,j=0;i<v.length;i+=3,j+=5){const x=v[i],y=v[i+1],z=v[i+2],cx=m[0]*x+m[4]*y+m[8]*z+m[12],cy=m[1]*x+m[5]*y+m[9]*z+m[13],cz=m[2]*x+m[6]*y+m[10]*z+m[14];projected[j]=w/2+cx/-cz*f/camera.aspect*w/2;projected[j+1]=h/2-cy/-cz*f*h/2;projected[j+2]=cz;projected[j+3]=cx;projected[j+4]=cy}
 const idx=mesh.i;for(let i=0;i<idx.length;i+=3){const a=idx[i]*5,b=idx[i+1]*5,c=idx[i+2]*5,ax=projected[a],ay=projected[a+1],bx=projected[b],by=projected[b+1],cx=projected[c],cy=projected[c+1];const area=(bx-ax)*(cy-ay)-(by-ay)*(cx-ax);if(mesh.side!==2&&area>=0)continue;if(Math.abs(area)<.015)continue;
 const ux=projected[b+3]-projected[a+3],uy=projected[b+4]-projected[a+4],uz=projected[b+2]-projected[a+2],vx=projected[c+3]-projected[a+3],vy=projected[c+4]-projected[a+4],vz=projected[c+2]-projected[a+2];const nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,len=Math.hypot(nx,ny,nz)||1;const intensity=.42+.78*Math.max(0,(nx*.25+ny*.65+nz*.72)/len);const colors=mesh.rgb.map(n=>Math.round(Math.min(255,(n*1.28+32)*intensity)));faces.push({z:(projected[a+2]+projected[b+2]+projected[c+2])/3,pts:[ax,ay,bx,by,cx,cy],color:colors,depths:[-1/projected[a+2],-1/projected[b+2],-1/projected[c+2]]});}
 }}const pw=canvas.width,ph=canvas.height,image=ctx.createImageData(pw,ph),pixels=image.data,depth=new Float32Array(pw*ph);
 for(const face of faces){const a=face.pts.map(v=>v*dpr),[ax,ay,bx,by,cx,cy]=a;const denominator=(by-cy)*(ax-cx)+(cx-bx)*(ay-cy);if(Math.abs(denominator)<.01)continue;const xmin=Math.max(0,Math.floor(Math.min(ax,bx,cx))),xmax=Math.min(pw-1,Math.ceil(Math.max(ax,bx,cx))),ymin=Math.max(0,Math.floor(Math.min(ay,by,cy))),ymax=Math.min(ph-1,Math.ceil(Math.max(ay,by,cy)));for(let y=ymin;y<=ymax;y++)for(let x=xmin;x<=xmax;x++){const u=((by-cy)*(x+.5-cx)+(cx-bx)*(y+.5-cy))/denominator,v=((cy-ay)*(x+.5-cx)+(ax-cx)*(y+.5-cy))/denominator,w=1-u-v;if(u<-.0001||v<-.0001||w<-.0001)continue;const q=u*face.depths[0]+v*face.depths[1]+w*face.depths[2],i=y*pw+x;if(q<=depth[i])continue;depth[i]=q;const j=i*4;pixels[j]=face.color[0];pixels[j+1]=face.color[1];pixels[j+2]=face.color[2];pixels[j+3]=255;}}
 ctx.putImageData(image,0,0);wrapper.dataset.rendered='true';wrapper.dataset.progress=p.toFixed(3);document.body.classList.add('ready');document.querySelector('#render-loading')?.setAttribute('hidden','');}
 function invalidate(){if(!pending)pending=requestAnimationFrame(draw)}control.invalidate=invalidate;new ResizeObserver(invalidate).observe(wrapper);invalidate();return wrapper;
}
